export const UserActionTypes = {
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  USER_AUTH_ERROR: 'USER_AUTH_ERROR',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  PROFILE_ERROR: 'PROFILE_ERROR'
}

export const PostActionTypes = {
  CREATE_POST: 'CREATE_POST',
  DELETE_POST: 'DELETE_POST',
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_POST: 'FETCH_POST',
  CREATE_COMMENT: 'CREATE_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  UPDATE_LIKES: 'UPDATE_LIKES',
  POST_ERROR: 'POST_ERROR'
}

export const CLEAR_ERROR = 'CLEAR_ERROR'
