const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  USER_AUTH_ERROR: 'USER_AUTH_ERROR',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE'
  // CHECK_USER_SESSION: 'CHECK_USER_SESSION'
}

export default UserActionTypes
